version: "3.0"
   
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    container_name: interview_bo_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: interview_bo_api
    build: .
    command:
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/code
      - ./files:/files
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  
